# Generated by Django 6.0.2 on 2026-02-19 04:13

import django.db.models.deletion
import vrlapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='10-digit mobile number', max_length=10, validators=[vrlapp.models.validate_phone_number])),
                ('address', models.TextField(help_text='Complete address including door number, street, area')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10, validators=[vrlapp.models.validate_phone_number])),
                ('address', models.TextField(help_text='Complete pickup address')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('parcel_description', models.TextField(help_text='Description of items in parcel')),
                ('parcel_weight', models.CharField(help_text='Weight (e.g., 2.5 kg, 500g, etc.)', max_length=50)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated value of parcel (optional)', max_digits=8, null=True)),
                ('preferred_pickup_date', models.DateField(help_text='Date of pickup')),
                ('preferred_pickup_time', models.TimeField(help_text='Preferred time slot')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin remarks', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pickup Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(help_text='Admin who changed the status', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pickup_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='vrlapp.pickuprequest')),
            ],
            options={
                'verbose_name_plural': 'Request Status History',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pickuprequest',
            index=models.Index(fields=['status', '-requested_at'], name='vrlapp_pick_status_926533_idx'),
        ),
        migrations.AddIndex(
            model_name='pickuprequest',
            index=models.Index(fields=['customer', '-requested_at'], name='vrlapp_pick_custome_382047_idx'),
        ),
    ]
