# Generated by Django 6.0.2 on 2026-02-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrlapp', '0003_customerprofile_email_verified_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeststatushistory',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='requeststatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], max_length=20, null=True),
        ),
    ]
